### ISSUE TITLE
Often gutenberg.run is very slow to load and many times will not load a PR

### ISSUE THREAD

**Issue by paaljoachim** [aduth/gutenberg.run#10]
I happen to make an issue at the Gutenberg github:
https://github.com/WordPress/gutenberg/issues/25225

Bottom line is that often times a PR will take a long time to load, and often times end up with an error.
Gutenberg.run is a great place to easily test PR features making it easier to give feedback before a feature is merged.

**Comment by aduth** [comment]
Thanks for flagging this. I discovered there was an error being caused by an upgrade of one of Gutenberg's dependencies requiring a newer version of Node.js than installed in the Gutenberg Run container images. I've rebuilt the images to install the latest version of Node.js, and at least in my testing it appears to have resolved the error. The build still takes quite a while to run, though I'm not sure there's an immediately actionable solution to this.
