### ISSUE TITLE
Changes from my Gutenberg PR weren't included Gutenberg.run ? 

### ISSUE THREAD

**Issue by skorasaurus** [aduth/gutenberg.run#3]
hi, 

Thanks for making this. This is really useful for testing out pull requests without having to make an manually making a testing environment or pulling in a PR into your own testing environment.  

I want to solicit feedback to some acquaintances for a [pull request that I made](https://github.com/WordPress/gutenberg/pull/18635) and share a testing environment for them on their browsers but the changes in my pull request didn't appear to load when I ran www.gutenberg.run. Perhaps I'm misunderstanding the purpose of gutenberg.run. :) 

What I expected:
- The changes in my pull request to appear in this instance of Gutenberg (specifically the `required` attribute in a search block, as I added in https://github.com/WordPress/gutenberg/pull/18635/commits/39b414665bc075b08ebb927e4d05a9219219371e 

What happened: 
- When I created a new post with a new search box in it; I inspect the source, and it appears as if this instance of gutenberg isn't including my pull request. 

(the link to my post is http://ncqtoqm3.gutenberg.run/2019/12/24/hi-everybody/) 

How to reproduce: 

1. visit www.gutenberg.run ; enter in 18635
2. once loaded, create a new post, add search block to it; publish. 
3. view newly published post visit source code, verify that the required attribute is not included.

**Comment by SchneiderSam** [comment]
Yes I understand and expected the same. But it doesn't work...

**Comment by aduth** [comment]
What I've observed so far is that if a build fails for one reason or another, a site will often still be provisioned, but it will be using the block editor for the stable release of WordPress, rather than the version of the plugin built from the pull request branch. You can usually confirm whether this is the case by visiting the Plugins screen to see whether Gutenberg is installed and activated. 

There are a few issues to address here:

- Prevent the build errors in the first place. There are a few intermittent issues which I've encountered which can contribute to this.
- Try to avoid creating a site when the build fails. 
- Maybe on Gutenberg's end, a better indication on the editor screen on whether the editor is running from the plugin.

**Comment by aduth** [comment]
Based on errors from the logs, I made some adjustments in 5735a6a59745d2cc3d19c34aecbd2592d9d82c45 which, at least anecdotally from my end seem to resolve some issues with "Error!" I had been encountering earlier in the day. I'd suggest to give it another try and see if you have any better luck this time.

**Comment by SchneiderSam** [comment]
Cool. Now it works.

**Comment by skorasaurus** [comment]
Thanks, it's now working as expected!
